cmake_minimum_required(VERSION 3.8)
project(rm_nav_planning)
find_package(ament_cmake REQUIRED)
find_package(Eigen3 REQUIRED)
add_library(timed_trajectory src/path_preprocessor.cpp)
target_include_directories(timed_trajectory PUBLIC include)
target_link_libraries(timed_trajectory PUBLIC Eigen3::Eigen)
add_executable(timed_trajectory_test test/timed_trajectory_test.cpp)
target_link_libraries(timed_trajectory_test timed_trajectory)
add_executable(path_preprocessor_test test/path_preprocessor_test.cpp)
target_link_libraries(path_preprocessor_test timed_trajectory)
enable_testing()
add_test(NAME timed_trajectory_test COMMAND timed_trajectory_test)
add_test(NAME path_preprocessor_test COMMAND path_preprocessor_test)
install(TARGETS timed_trajectory path_preprocessor_test timed_trajectory_test
  ARCHIVE DESTINATION lib RUNTIME DESTINATION lib/${PROJECT_NAME})
install(DIRECTORY include/ DESTINATION include)
install(FILES README.md DESTINATION share/${PROJECT_NAME})
ament_package()
