cmake_minimum_required(VERSION 3.8)
project(rm_nav_control)
find_package(ament_cmake REQUIRED)
add_library(command_synthesizer INTERFACE)
target_include_directories(command_synthesizer INTERFACE include)
add_executable(command_synthesizer_test test/command_synthesizer_test.cpp)
target_link_libraries(command_synthesizer_test command_synthesizer)
enable_testing()
add_test(NAME command_synthesizer_test COMMAND command_synthesizer_test)
install(TARGETS command_synthesizer_test RUNTIME DESTINATION lib/${PROJECT_NAME})
install(DIRECTORY include/ DESTINATION include)
install(FILES README.md DESTINATION share/${PROJECT_NAME})
ament_package()
